name: Deploy

on:
  push:
    branches:
      - main

  # Run tests for any PRs.
  pull_request:
  
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: lnbits-discord-bot

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Create env file
      run: |
        touch .env
        echo "${{ secrets.ENV }}" > .env
        
    - name: Build image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME
      #run: docker build . --build-arg ACCESS_TOKEN_GITHUB="${{ secrets.ACCESS_TOKEN_GITHUB }}" --file Dockerfile --tag $IMAGE_NAME

    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Push image
      run: |
         IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
         # Change all uppercase to lowercase
         IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
         # Strip git ref prefix from version
         VERSION=master
         echo IMAGE_ID=$IMAGE_ID
         echo VERSION=$VERSION
         docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
         docker push $IMAGE_ID:$VERSION
         
    - name: Deploy to Host
      #run: docker-compose pull && docker-compose up -d
      run: docker-compose -f docker-compose.yml pull && docker-compose -f docker-compose.yml up -d
