name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository
      
    - name: Create env file
      run: |
        touch .env
        echo "${{ secrets.ENV }}" > .env      

    - uses: actions/setup-node@v1
      name: Setup Node.js 12
      with:
        node-version: '12'

    - run: npm install

    - run: npm run build --if-present

    - run: npm run test --if-present
